version: '3.8'
services:

  backend:
    build:
      context: .
    image: simple-be
    ports:
      - "8080:8080"
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge