name: Unit Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build backend image
        run: docker compose build backend

      - name: Start test db container
        run: docker compose up -d --wait db_test

      - name: Run Tests
        env:
          TEST_DATABASE_URL: "host=localhost port=5435 user=postgres password=postgres dbname=testdb sslmode=disable"
        run: go test -tags=postgres ./test -v -race -count=1

      - name: Cleanup
        if: always()
        run: docker compose down -v